name: yama
description: Yet Another Manga Application.

publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_downloader: ^1.11.6
  http: ^1.2.1
  path: ^1.9.0
  photo_view: ^0.14.0
  provider: ^6.1.2
  sqflite: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - .env

  fonts:
    - family: PaletteMosaic
      fonts:
        - asset: assets/fonts/PaletteMosaic-Regular.ttf