name: yama
description: Yet Another Manga Application.

publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  flutter:
    sdk: flutter
  http: ^1.2.1
  photo_view: ^0.14.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: PaletteMosaic
      fonts:
        - asset: assets/fonts/PaletteMosaic-Regular.ttf
